/*!
 * Stockfish copyright T. Romstad, M. Costalba, J. Kiiski, G. Linscott
 * and other contributors.
 *
 * Released under the GNU General Public License v3.
 *
 * Compiled to JavaScript and WebAssembly by Niklas Fiekas
 * <niklas.fiekas@backscattering.de> using Emscripten.
 *
 * https://github.com/niklasf/stockfish.wasm
 */

var Stockfish = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


function d(){k.buffer!=l&&n(k.buffer);return aa}function t(){k.buffer!=l&&n(k.buffer);return ba}function w(){k.buffer!=l&&n(k.buffer);return da}function y(){k.buffer!=l&&n(k.buffer);return ea}function fa(){k.buffer!=l&&n(k.buffer);return ha}null;var z;z||(z=typeof Stockfish !== 'undefined' ? Stockfish : {});var ia,ja;z.ready=new Promise(function(a,b){ia=a;ja=b});
(function(){function a(){var g=e.shift();if(!b&&void 0!==g){if("quit"===g)return z.terminate();var m=z.ccall("uci_command","number",["string"],[g]);m&&e.unshift(g);h=m?2*h:1;setTimeout(a,h)}}var b=!1,c=[];z.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var m=0;m<c.length;m++)c[m](g)})};z.addMessageListener=function(g){c.push(g)};z.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};z.terminate=function(){b=!0;A.Ba()};var e=[],h=1;z.postMessage=function(g){e.push(g)};
z.postRun=function(){z.postMessage=function(g){e.push(g);1===e.length&&a()};a()}})();var B={},C;for(C in z)z.hasOwnProperty(C)&&(B[C]=z[C]);var ka=[],la="./this.program";function ma(a,b){throw b;}var na="object"===typeof window,D="function"===typeof importScripts,E="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,F=z.ENVIRONMENT_IS_PTHREAD||!1,G="";function oa(a){return z.locateFile?z.locateFile(a,G):G+a}var H,I,J,K;
if(E){G=D?require("path").dirname(G)+"/":__dirname+"/";H=function(a,b){J||(J=require("fs"));K||(K=require("path"));a=K.normalize(a);return J.readFileSync(a,b?null:"utf8")};I=function(a){a=H(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(la=process.argv[1].replace(/\\/g,"/"));ka=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof M))throw a;});process.on("unhandledRejection",N);ma=function(a,b){if(O())throw process.exitCode=a,
b;process.exit(a)};z.inspect=function(){return"[Emscripten Module object]"};var pa;try{pa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=pa.Worker}else if(na||D)D?G=self.location.href:"undefined"!==typeof document&&document.currentScript&&(G=document.currentScript.src),_scriptDir&&(G=_scriptDir),0!==G.indexOf("blob:")?G=G.substr(0,G.lastIndexOf("/")+1):G="",E?(H=function(a,
b){J||(J=require("fs"));K||(K=require("path"));a=K.normalize(a);return J.readFileSync(a,b?null:"utf8")},I=function(a){a=H(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(H=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},D&&(I=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));E&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);
var qa=z.print||console.log.bind(console),P=z.printErr||console.warn.bind(console);for(C in B)B.hasOwnProperty(C)&&(z[C]=B[C]);B=null;z.arguments&&(ka=z.arguments);z.thisProgram&&(la=z.thisProgram);z.quit&&(ma=z.quit);var ra,Q;z.wasmBinary&&(Q=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!==typeof WebAssembly&&N("no native wasm support detected");var k,ta,ua=!1,R;function assert(a,b){a||N("Assertion failed: "+b)}
function va(a){var b=z["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}function wa(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var xa="undefined"!==typeof TextDecoder?new wa("utf8"):void 0;
function ya(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&xa)return xa.decode(a.subarray(b,c));for(e="";b<c;){var h=a[b++];if(h&128){var g=a[b++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|g);else{var m=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|m:(h&7)<<18|g<<12|m<<6|a[b++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e}function S(a){return a?ya(t(),a,void 0):""}
function za(a,b,c,e){if(0<e){e=c+e-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new wa("utf-16le");function Ba(a){var b=Aa(a)+1,c=T(b);za(a,d(),c,b);return c}function Ca(a,b){d().set(a,b)}var l,aa,ba,da,ea,ha;F&&(l=z.buffer);
function n(a){l=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=new Int16Array(a);z.HEAP32=da=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAPU32=ea=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=ha=new Float64Array(a)}var Da=z.INITIAL_MEMORY||71303168;
if(F)k=z.wasmMemory,l=z.buffer;else if(z.wasmMemory)k=z.wasmMemory;else if(k=new WebAssembly.Memory({initial:Da/65536,maximum:32768,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw P("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),E&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");k&&(l=k.buffer);Da=l.byteLength;n(l);var U,Ea=[],Fa=[],Ga=[],Ha=[],Ia=0;function O(){return noExitRuntime||0<Ia}function Ja(){var a=z.preRun.shift();Ea.unshift(a)}var V=0,Ka=null,W=null;z.preloadedImages={};z.preloadedAudios={};function N(a){if(F)postMessage({cmd:"onAbort",arg:a});else if(z.onAbort)z.onAbort(a);P(a);ua=!0;R=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ja(a);throw a;}
function La(){return X.startsWith("data:application/octet-stream;base64,")}var X;X="stockfish.wasm";La()||(X=oa(X));function Ma(){var a=X;try{if(a==X&&Q)return new Uint8Array(Q);if(I)return I(a);throw"both async and sync fetching of the wasm failed";}catch(b){N(b)}}
function Na(){return Q||!na&&!D||"function"!==typeof fetch?Promise.resolve().then(function(){return Ma()}):fetch(X,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+X+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}var Oa={};function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(z);else{var c=b.fb;"number"===typeof c?void 0===b.oa?U.get(c)():U.get(c)(b.oa):c(void 0===b.oa?null:b.oa)}}}
function Qa(a,b){if(0>=a||a>d().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(w(),Y>>2),e=0;if(c==a&&Atomics.compareExchange(w(),Y>>2,c,0)==c&&(--b,e=1,0>=b))return 1;a=Atomics.notify(w(),a>>2,b);if(0<=a)return a+e;throw"Atomics.notify returned an unexpected value "+a;}z._emscripten_futex_wake=Qa;
function Ra(a){if(F)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=A.ha[a];b&&(w()[a+8>>2]=0,A.va(b.worker))}function Sa(a){Ta(a)}z._exit=Sa;function Ua(a){a instanceof M||"unwind"==a||(P("exception thrown: "+a),ma(1,a))}
var A={ia:[],ja:[],Da:[],Na:function(){for(var a=0;1>a;++a)A.Ea()},Oa:function(a){Va(a,!D,1)},Pa:function(){A.receiveObjectTransfer=A.Ra;A.threadInit=A.Va;A.setExitStatus=A.Ta},ha:{},Ca:[],Ta:function(a){R=a},Ba:function(){for(var a in A.ha){var b=A.ha[a];b&&b.worker&&A.va(b.worker)}A.ha={};for(a=0;a<A.ia.length;++a){var c=A.ia[a];c.terminate()}A.ia=[];for(a=0;a<A.ja.length;++a)c=A.ja[a],b=c.ga,c.terminate(),A.Aa(b);A.ja=[]},Aa:function(a){a&&(a.la&&Wa(a.la),a.la=0,a.za&&a.ka&&Wa(a.ka),a.ka=0,a.worker&&
(a.worker.ga=null))},va:function(a){A.Sa(function(){delete A.ha[a.ga.la];A.ia.push(a);A.ja.splice(A.ja.indexOf(a),1);A.Aa(a.ga);a.ga=void 0})},Sa:function(a){w()[Xa>>2]=0;try{a()}finally{w()[Xa>>2]=1}},Ra:function(){},Va:function(){for(var a in A.Da)A.Da[a]()},Ha:function(a,b){a.onmessage=function(c){var e=c.data,h=e.cmd;a.ga&&(A.Ja=a.ga.la);if(e.targetThread&&e.targetThread!=Ya()){var g=A.ha[e.mb];g?g.worker.postMessage(c.data,e.transferList):P('Internal error! Worker sent a message "'+h+'" to target pthread '+
e.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===h)Za();else if("spawnThread"===h)$a(c.data);else if("cleanupThread"===h)Ra(e.thread);else if("killThread"===h){c=e.thread;if(F)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";w()[c+8>>2]=0;e=A.ha[c];delete A.ha[c];e.worker.terminate();A.Aa(e);A.ja.splice(A.ja.indexOf(e.worker),1);e.worker.ga=void 0}else if("cancelThread"===
h){c=e.thread;if(F)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";A.ha[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===h)a.loaded=!0,b&&b(a),a.pa&&(a.pa(),delete a.pa);else if("print"===h)qa("Thread "+e.threadId+": "+e.text);else if("printErr"===h)P("Thread "+e.threadId+": "+e.text);else if("alert"===h)alert("Thread "+e.threadId+": "+e.text);else if("exit"===h)a.ga&&Atomics.load(y(),
a.ga.la+60>>2)&&A.va(a);else if("exitProcess"===h)try{Ta(e.returnCode)}catch(m){Ua(m)}else if("cancelDone"===h)A.va(a);else if("setimmediate"===c.data.target)a.postMessage(c.data);else if("onAbort"===h){if(z.onAbort)z.onAbort(e.arg)}else P("worker sent an unknown command "+h);A.Ja=void 0};a.onerror=function(c){P("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};E&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));
a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:k,wasmModule:ta})},Ea:function(){var a=oa("stockfish.worker.js");A.ia.push(new Worker(a))},La:function(){0==A.ia.length&&(A.Ea(),A.Ha(A.ia[0]));return A.ia.pop()}};z.establishStackSpace=function(a,b){ab(a,b);bb(a)};z.invokeEntryPoint=function(a,b){return U.get(a)(b)};var cb;cb=E?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:F?function(){return performance.now()-z.__performance_now_clock_drift}:function(){return performance.now()};
function $a(a){if(F)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=A.La();if(!b)return 6;if(void 0!==b.ga)throw"Internal error!";if(!a.ua)throw"Internal error, no pthread ptr!";A.ja.push(b);var c=a.ka+a.ma,e=A.ha[a.ua]={worker:b,ka:a.ka,ma:a.ma,za:a.za,la:a.ua},h=e.la>>2;Atomics.store(y(),h+15,a.detached);Atomics.store(y(),h+19,a.ma);Atomics.store(y(),h+18,c);Atomics.store(y(),h+25,a.ma);Atomics.store(y(),h+27,c);Atomics.store(y(),h+28,a.detached);
b.ga=e;var g={cmd:"run",start_routine:a.Ua,arg:a.oa,threadInfoStruct:a.ua,stackBase:a.ka,stackSize:a.ma};b.pa=function(){g.time=performance.now();b.postMessage(g,a.$a)};b.loaded&&(b.pa(),delete b.pa);return 0}
function db(a,b,c){if(0>=a||a>d().length||a&1)return-28;if(na){if(Atomics.load(w(),a>>2)!=b)return-6;var e=performance.now();c=e+c;for(Atomics.exchange(w(),Y>>2,a);;){e=performance.now();if(e>c)return Atomics.exchange(w(),Y>>2,0),-73;e=Atomics.exchange(w(),Y>>2,0);if(0==e)break;Za();if(Atomics.load(w(),a>>2)!=b)return-6;Atomics.exchange(w(),Y>>2,a)}return 0}a=Atomics.wait(w(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function eb(){E||D||(ra||(ra={}),ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ra["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,P("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function fb(a,b){if(!a)return P("pthread_join attempted on a null thread pointer!"),71;if(F&&Ya()==a)return P("PThread "+a+" is attempting to join to itself!"),16;if(!F&&gb()==a)return P("Main thread "+a+" is attempting to join to itself!"),16;if(w()[a+8>>2]!==a)return P("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(y(),a+60>>2))return P("Attempted to join thread "+a+", which was already detached!"),28;for(eb();;){var c=
Atomics.load(y(),a+0>>2);if(1==c)return b&&(c=Atomics.load(y(),a+88>>2),w()[b>>2]=c),Atomics.store(y(),a+60>>2,1),F?postMessage({cmd:"cleanupThread",thread:a}):Ra(a),0;hb();F||Za();db(a+0,c,F?100:1)}}var ib=[null,[],[]],jb={};function kb(a,b,c){return F?Z(2,1,a,b,c):0}function lb(a,b,c){return F?Z(3,1,a,b,c):0}function mb(a,b,c){if(F)return Z(4,1,a,b,c)}function Z(a,b){for(var c=arguments.length-2,e=nb(),h=T(8*c),g=h>>3,m=0;m<c;m++){var p=arguments[2+m];fa()[g+m]=p}c=ob(a,c,h,b);bb(e);return c}
var pb=[],qb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function rb(a){a=2<a?S(a):a;return qb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function sb(a,b,c){var e=rb(a);if(!e)return-4;e.ta&&(w()[e.ta>>2]=b,w()[e.ta+4>>2]=c);if(e.Ia||!e.bb)e.Ia&&(e=e.Ia),a=!1,e.sa&&e.sa.ra&&(a=e.sa.ra.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=c,a&&e.sa.ra.viewport(0,0,b,c);else{if(e.ta){e=w()[e.ta+8>>2];a=a?S(a):"";var h=nb(),g=T(12),m=0;if(a){m=Aa(a)+1;var p=tb(m);za(a,t(),p,m);m=p}w()[g>>2]=m;w()[g+4>>2]=b;w()[g+8>>2]=c;ub(0,e,657457152,0,m,g);bb(h);return 1}return-4}return 0}
function vb(a,b,c){return F?Z(5,1,a,b,c):sb(a,b,c)}function wb(a){if(!ua)try{if(a(),F&&!O())try{F?xb(R):Ta(R)}catch(b){Ua(b)}}catch(b){Ua(b)}}function yb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,h,g){b.drawArraysInstancedANGLE(c,e,h,g)},a.drawElementsInstanced=function(c,e,h,g,m){b.drawElementsInstancedANGLE(c,e,h,g,m)})}
function zb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ab(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function Bb(a,b){a.Ga||(a.Ga=a.getContext,a.getContext=function(e,h){h=a.Ga(e,h);return"webgl"==e==h instanceof WebGLRenderingContext?h:null});var c=a.getContext("webgl",b);return c?Cb(c,b):0}function Cb(a,b){var c=tb(8);w()[c+4>>2]=Ya();var e={hb:c,attributes:b,version:b.Qa,ra:a};a.canvas&&(a.canvas.sa=e);("undefined"===typeof b.Fa||b.Fa)&&Db(e);return c}
function Db(a){a||(a=Eb);if(!a.Ma){a.Ma=!0;var b=a.ra;yb(b);zb(b);Ab(b);b.cb=b.getExtension("EXT_disjoint_timer_query");b.jb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Eb,Gb=["default","low-power","high-performance"],Hb={};
function Ib(){if(!Jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:la||"./this.program"},b;for(b in Hb)void 0===Hb[b]?delete a[b]:a[b]=Hb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Jb=c}return Jb}var Jb;
function Kb(a,b){if(F)return Z(6,1,a,b);var c=0;Ib().forEach(function(e,h){var g=b+c;h=w()[a+4*h>>2]=g;for(g=0;g<e.length;++g)d()[h++>>0]=e.charCodeAt(g);d()[h>>0]=0;c+=e.length+1});return 0}function Lb(a,b){if(F)return Z(7,1,a,b);var c=Ib();w()[a>>2]=c.length;var e=0;c.forEach(function(h){e+=h.length+1});w()[b>>2]=e;return 0}function Mb(a){return F?Z(8,1,a):0}function Nb(a,b,c,e){if(F)return Z(9,1,a,b,c,e);a=jb.gb(a);b=jb.eb(a,b,c);w()[e>>2]=b;return 0}
function Ob(a,b,c,e,h){if(F)return Z(10,1,a,b,c,e,h)}function Pb(a,b,c,e){if(F)return Z(11,1,a,b,c,e);for(var h=0,g=0;g<c;g++){for(var m=w()[b+8*g>>2],p=w()[b+(8*g+4)>>2],x=0;x<p;x++){var r=t()[m+x],u=ib[a];0===r||10===r?((1===a?qa:P)(ya(u,0)),u.length=0):u.push(r)}h+=p}w()[e>>2]=h;return 0}function Qb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rb(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var Sb=[31,29,31,30,31,30,31,31,30,31,30,31],Tb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ub(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Qb(a.getFullYear())?Sb:Tb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Vb(a,b,c,e){function h(f,q,v){for(f="number"===typeof f?f.toString():f||"";f.length<q;)f=v[0]+f;return f}function g(f,q){return h(f,q,"0")}function m(f,q){function v(Fb){return 0>Fb?-1:0<Fb?1:0}var L;0===(L=v(f.getFullYear()-q.getFullYear()))&&0===(L=v(f.getMonth()-q.getMonth()))&&(L=v(f.getDate()-q.getDate()));return L}function p(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function x(f){f=Ub(new Date(f.fa+1900,0,1),f.ya);var q=new Date(f.getFullYear()+1,0,4),v=p(new Date(f.getFullYear(),0,4));q=p(q);return 0>=m(v,f)?0>=m(q,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var r=w()[e+40>>2];e={Ya:w()[e>>2],Xa:w()[e+4>>2],wa:w()[e+8>>2],qa:w()[e+12>>2],na:w()[e+16>>2],fa:w()[e+20>>2],xa:w()[e+24>>2],ya:w()[e+28>>2],nb:w()[e+
32>>2],Wa:w()[e+36>>2],Za:r?S(r):""};c=S(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in r)c=c.replace(new RegExp(u,"g"),r[u]);var ca="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
sa="January February March April May June July August September October November December".split(" ");r={"%a":function(f){return ca[f.xa].substring(0,3)},"%A":function(f){return ca[f.xa]},"%b":function(f){return sa[f.na].substring(0,3)},"%B":function(f){return sa[f.na]},"%C":function(f){return g((f.fa+1900)/100|0,2)},"%d":function(f){return g(f.qa,2)},"%e":function(f){return h(f.qa,2," ")},"%g":function(f){return x(f).toString().substring(2)},"%G":function(f){return x(f)},"%H":function(f){return g(f.wa,
2)},"%I":function(f){f=f.wa;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":function(f){return g(f.qa+Rb(Qb(f.fa+1900)?Sb:Tb,f.na-1),3)},"%m":function(f){return g(f.na+1,2)},"%M":function(f){return g(f.Xa,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.wa&&12>f.wa?"AM":"PM"},"%S":function(f){return g(f.Ya,2)},"%t":function(){return"\t"},"%u":function(f){return f.xa||7},"%U":function(f){var q=new Date(f.fa+1900,0,1),v=0===q.getDay()?q:Ub(q,7-q.getDay());f=new Date(f.fa+1900,f.na,f.qa);return 0>
m(v,f)?g(Math.ceil((31-v.getDate()+(Rb(Qb(f.getFullYear())?Sb:Tb,f.getMonth()-1)-31)+f.getDate())/7),2):0===m(v,q)?"01":"00"},"%V":function(f){var q=new Date(f.fa+1901,0,4),v=p(new Date(f.fa+1900,0,4));q=p(q);var L=Ub(new Date(f.fa+1900,0,1),f.ya);return 0>m(L,v)?"53":0>=m(q,L)?"01":g(Math.ceil((v.getFullYear()<f.fa+1900?f.ya+32-v.getDate():f.ya+1-v.getDate())/7),2)},"%w":function(f){return f.xa},"%W":function(f){var q=new Date(f.fa,0,1),v=1===q.getDay()?q:Ub(q,0===q.getDay()?1:7-q.getDay()+1);f=
new Date(f.fa+1900,f.na,f.qa);return 0>m(v,f)?g(Math.ceil((31-v.getDate()+(Rb(Qb(f.getFullYear())?Sb:Tb,f.getMonth()-1)-31)+f.getDate())/7),2):0===m(v,q)?"01":"00"},"%y":function(f){return(f.fa+1900).toString().substring(2)},"%Y":function(f){return f.fa+1900},"%z":function(f){f=f.Wa;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Za},"%%":function(){return"%"}};for(u in r)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),r[u](e)));u=Wb(c);
if(u.length>b)return 0;Ca(u,a);return u.length-1}F||A.Na();var Xb=[null,function(a,b){if(F)return Z(1,1,a,b)},kb,lb,mb,vb,Kb,Lb,Mb,Nb,Ob,Pb];function Wb(a){var b=Array(Aa(a)+1);za(a,b,0,b.length);return b}
var ac={c:function(a,b,c,e){N("Assertion failed: "+S(a)+", at: "+[b?S(b):"unknown filename",c,e?S(e):"unknown function"])},z:function(a,b){A.Ca.push(function(){U.get(a)(b)})},j:function(a,b,c,e){if("undefined"===typeof SharedArrayBuffer)return P("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var h=[];if(F&&0===h.length)return Yb(687865856,a,b,c,e);var g=0,m=0;if(b&&-1!=b){var p=w()[b>>2];p+=81920;g=w()[b+8>>2];m=0!==w()[b+12>>2]}else p=2097152;(b=0==g)?g=
Zb(16,p):(g-=p,assert(0<g));a={ka:g,ma:p,za:b,detached:m,Ua:c,ua:a,oa:e,$a:h};return F?(a.ab="spawnThread",postMessage(a,h),0):$a(a)},C:function(){postMessage({cmd:"exit"})},m:function(){for(;0<A.Ca.length;)A.Ca.pop()()},A:function(a,b){return fb(a,b)},l:kb,t:lb,u:mb,I:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(F)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=A.ha[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){N()},
q:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=cb();else return w()[$b()>>2]=28,-1;w()[b>>2]=a/1E3|0;w()[b+4>>2]=a%1E3*1E6|0;return 0},y:eb,i:function(){},e:db,d:Qa,f:cb,o:function(a,b,c){t().copyWithin(a,b,b+c)},D:function(a,b,c){pb.length=b;c>>=3;for(var e=0;e<b;e++)pb[e]=fa()[c+e];return(0>a?Oa[-a-1]:Xb[a]).apply(null,pb)},p:function(a){var b=t().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&
(e+=65536-e%65536);a:{try{k.grow(Math.min(2147483648,e)-l.byteLength+65535>>>16);n(k.buffer);var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},E:function(a,b,c){return rb(a)?sb(a,b,c):vb(a,b,c)},h:function(){},H:function(a,b,c){Ia+=1;return setTimeout(function(){--Ia;wb(function(){U.get(a)(c)})},b)},B:function(){throw"unwind";},F:function(a,b){b>>=2;var c=w()[b+6];b={alpha:!!w()[b],depth:!!w()[b+1],stencil:!!w()[b+2],antialias:!!w()[b+3],premultipliedAlpha:!!w()[b+4],preserveDrawingBuffer:!!w()[b+
5],powerPreference:Gb[c],failIfMajorPerformanceCaveat:!!w()[b+7],Qa:w()[b+8],ib:w()[b+9],Fa:w()[b+10],Ka:w()[b+11],kb:w()[b+12],lb:w()[b+13]};a=rb(a);return!a||b.Ka?0:Bb(a,b)},w:Kb,x:Lb,g:Sa,k:Mb,s:Nb,n:Ob,r:Pb,G:function(a){A.Oa(a)},a:k||z.wasmMemory,v:function(a,b,c,e){return Vb(a,b,c,e)}};
(function(){function a(h,g){z.asm=h.exports;U=z.asm.P;Fa.unshift(z.asm.J);A.Da.push(z.asm.O);ta=g;if(!F){var m=A.ia.length;A.ia.forEach(function(p){A.Ha(p,function(){if(!--m&&(V--,z.monitorRunDependencies&&z.monitorRunDependencies(V),0==V&&(null!==Ka&&(clearInterval(Ka),Ka=null),W))){var x=W;W=null;x()}})})}}function b(h){a(h.instance,h.module)}function c(h){return Na().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(h,function(g){P("failed to asynchronously prepare wasm: "+
g);N(g)})}var e={a:ac};F||(V++,z.monitorRunDependencies&&z.monitorRunDependencies(V));if(z.instantiateWasm)try{return z.instantiateWasm(e,a)}catch(h){return P("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return Q||"function"!==typeof WebAssembly.instantiateStreaming||La()||"function"!==typeof fetch?c(b):fetch(X,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,e).then(b,function(g){P("wasm streaming compile failed: "+g);P("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(ja);return{}})();z.___wasm_call_ctors=function(){return(z.___wasm_call_ctors=z.asm.J).apply(null,arguments)};z._main=function(){return(z._main=z.asm.K).apply(null,arguments)};var tb=z._malloc=function(){return(tb=z._malloc=z.asm.L).apply(null,arguments)},Wa=z._free=function(){return(Wa=z._free=z.asm.M).apply(null,arguments)};z._uci_command=function(){return(z._uci_command=z.asm.N).apply(null,arguments)};
z._emscripten_tls_init=function(){return(z._emscripten_tls_init=z.asm.O).apply(null,arguments)};z._emscripten_current_thread_process_queued_calls=function(){return(z._emscripten_current_thread_process_queued_calls=z.asm.Q).apply(null,arguments)};
var gb=z._emscripten_main_browser_thread_id=function(){return(gb=z._emscripten_main_browser_thread_id=z.asm.R).apply(null,arguments)},Yb=z._emscripten_sync_run_in_main_thread_4=function(){return(Yb=z._emscripten_sync_run_in_main_thread_4=z.asm.S).apply(null,arguments)},Za=z._emscripten_main_thread_process_queued_calls=function(){return(Za=z._emscripten_main_thread_process_queued_calls=z.asm.T).apply(null,arguments)},ob=z._emscripten_run_in_main_runtime_thread_js=function(){return(ob=z._emscripten_run_in_main_runtime_thread_js=
z.asm.U).apply(null,arguments)},ub=z.__emscripten_call_on_thread=function(){return(ub=z.__emscripten_call_on_thread=z.asm.V).apply(null,arguments)},xb=z.__emscripten_thread_exit=function(){return(xb=z.__emscripten_thread_exit=z.asm.W).apply(null,arguments)};z.___pthread_tsd_run_dtors=function(){return(z.___pthread_tsd_run_dtors=z.asm.X).apply(null,arguments)};
var Ya=z._pthread_self=function(){return(Ya=z._pthread_self=z.asm.Y).apply(null,arguments)},Va=z.__emscripten_thread_init=function(){return(Va=z.__emscripten_thread_init=z.asm.Z).apply(null,arguments)},hb=z._pthread_testcancel=function(){return(hb=z._pthread_testcancel=z.asm._).apply(null,arguments)},$b=z.___errno_location=function(){return($b=z.___errno_location=z.asm.$).apply(null,arguments)},nb=z.stackSave=function(){return(nb=z.stackSave=z.asm.aa).apply(null,arguments)},bb=z.stackRestore=function(){return(bb=
z.stackRestore=z.asm.ba).apply(null,arguments)},T=z.stackAlloc=function(){return(T=z.stackAlloc=z.asm.ca).apply(null,arguments)},ab=z._emscripten_stack_set_limits=function(){return(ab=z._emscripten_stack_set_limits=z.asm.da).apply(null,arguments)},Zb=z._memalign=function(){return(Zb=z._memalign=z.asm.ea).apply(null,arguments)},Xa=z.__emscripten_allow_main_runtime_queued_calls=25196,Y=z.__emscripten_main_thread_futex=1088404;
z.ccall=function(a,b,c,e){var h={string:function(r){var u=0;if(null!==r&&void 0!==r&&0!==r){var ca=(r.length<<2)+1,sa=u=T(ca);za(r,t(),sa,ca)}return u},array:function(r){var u=T(r.length);Ca(r,u);return u}};a=va(a);var g=[],m=0;if(e)for(var p=0;p<e.length;p++){var x=h[c[p]];x?(0===m&&(m=nb()),g[p]=x(e[p])):g[p]=e[p]}c=a.apply(null,g);return c=function(r){0!==m&&bb(m);return"string"===b?S(r):"boolean"===b?!!r:r}(c)};z.keepRuntimeAlive=O;z.PThread=A;z.PThread=A;z.wasmMemory=k;z.ExitStatus=M;var bc;
function M(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}W=function cc(){bc||dc();bc||(W=cc)};
function dc(a){function b(){if(!bc&&(bc=!0,z.calledRun=!0,!ua)){F||Pa(Fa);F||Pa(Ga);ia(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(ec){var c=a,e=z._main;c=c||[];var h=c.length+1,g=T(4*(h+1));w()[g>>2]=Ba(la);for(var m=1;m<h;m++)w()[(g>>2)+m]=Ba(c[m-1]);w()[(g>>2)+h]=0;try{var p=e(h,g);Ta(p,!0)}catch(x){Ua(x)}finally{}}if(!F){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;)c=z.postRun.shift(),Ha.unshift(c);Pa(Ha)}}}a=a||ka;if(!(0<V))if(F)ia(z),
F||Pa(Fa),postMessage({cmd:"loaded"});else{if(!F){if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ja();Pa(Ea)}0<V||(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},1);b()},1)):b())}}z.run=dc;function Ta(a,b){R=a;if(!b&&F)throw postMessage({cmd:"exitProcess",returnCode:a}),new M(a);O()||A.Ba();R=a;if(!O()){A.Ba();if(z.onExit)z.onExit(a);ua=!0}ma(a,new M(a))}
if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var ec=!0;z.noInitialRun&&(ec=!1);F&&(noExitRuntime=!1,A.Pa());dc();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
